# YAML configuration file with some sensible defaults, except Reddit app secrets.
# Each value can be replaced by environment variable (or variable in .env),
# of all nested keys separated by an "_", like "api_host", "api_reddit_default_load_count",
# "reddit_client_id", "reddit_client_secret" etc.

api:
  # Host where API will listen to requests
  host: 0.0.0.0
  # Port where API will listen to requests
  port: 8080
  reddit:
    # How many submissions are loaded with each request by default
    default_load_count: 50
    # Loaded subreddit when none is specified
    default_subreddit: all
reddit:
  client:
    # Reddit dev app ID used by Reddit client
    id:
    # Reddit dev app secret used by Reddit client
    secret:
    # User agent used by Reddit client
    user_agent: api
